export const barrios = [

    { localidad: "Medellín-San Javier", nombre: "80 De Marzo", estrato: 2, sector: "Occidente" },
    { localidad: "Medellín-Robledo", nombre: "Acapo Valdés", estrato: 3, sector: "Occidente" },
    { localidad: "Bello", nombre: "Altos De Niquia", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Manrique", nombre: "Andalucía", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Manrique", nombre: "Aranjuez", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Belén", nombre: "Belen Joaquinillos", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "Belen La Capilla", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "Belen La Gloria", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "Belén Las Violetas", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "Belén Rincón La Capilla", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "Belencito", estrato: 2, sector: "Occidente" },
    { localidad: "Bello", nombre: "Bello Playa Rica", estrato: 3, sector: "Norte" },
    { localidad: "Bello", nombre: "Bello, Trapiche", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-La Candelaria", nombre: "Bombona", estrato: 2, sector: "Centro" },
    { localidad: "Medellín-Belén", nombre: "Bosque", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-La Candelaria", nombre: "Boston", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-Buenos Aires", nombre: "Buenos Aires", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Buenos Aires", nombre: "Buenos Aires La Pastora", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Buenos Aires", nombre: "Buenos Aires Urba Ciudadela Del Este", estrato: 3, sector: "Nororiente" },
    { localidad: "Bello", nombre: "Bello Cabañas", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Manrique", nombre: "Caicedo", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Manrique", nombre: "Caicedo Santa Lucia", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Robledo", nombre: "Calasanz", estrato: 4, sector: "Occidente" },
    { localidad: "Medellín-Aranjuez", nombre: "Campo Valdes", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-La Candelaria", nombre: "Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-Castilla", nombre: "Castilla", estrato: 3, sector: "Noroccidente" },
    { localidad: "Medellín-Robledo", nombre: "Colinas De Calsanz", estrato: 4, sector: "Occidente" },
    { localidad: "Medellín-Robledo", nombre: "Colinita", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Laureles", nombre: "Conquistadores", estrato: 5, sector: "Occidente" },
    { localidad: "Medellín-Robledo", nombre: "Doce De Octubre", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "El Bosque", estrato: 3, sector: "Occidente" },
    { localidad: "Bello", nombre: "Bello El Paraiso", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-La Candelaria", nombre: "El Salvador", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-Manrique", nombre: "Enciso", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Manrique", nombre: "Enciso El Pinal", estrato: 3, sector: "Nororiente" },
    { localidad: "Envigado", nombre: "Envigado Obrero", estrato: 3, sector: "Sur" },
    { localidad: "Medellín-Manrique", nombre: "Francisco Antonio Zea", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Manrique", nombre: "Granizal", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-Guayabal", nombre: "Guayabal La Colinita", estrato: 3, sector: "Sur" },
    { localidad: "Medellín-La América", nombre: "La America", estrato: 4, sector: "Occidente" },
    { localidad: "Bello", nombre: "La Camila En Bello", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-La Candelaria", nombre: "La Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-Belén", nombre: "La Capilla", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Belén", nombre: "La Colinita", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Manrique", nombre: "La Francia", estrato: 2, sector: "Nororiente" },
    { localidad: "Bello", nombre: "La Gabriela", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-La Candelaria", nombre: "La Ladera", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-La Candelaria", nombre: "La Libertad", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-Manrique", nombre: "La Milagrosa", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-Robledo", nombre: "La Palma", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Manrique", nombre: "Las Margaritas", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-La Candelaria", nombre: "Las Palmas", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-La Candelaria", nombre: "Las Torres De Bombona", estrato: 2, sector: "Centro" },
    { localidad: "Bello", nombre: "Las Vegas Machado", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-La Candelaria", nombre: "Los Ceris", estrato: 3, sector: "Centro" },
    { localidad: "Bello", nombre: "Madera", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Manrique", nombre: "Manrique Central", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-Manrique", nombre: "Manrique, Oriental", estrato: 3, sector: "Nororiente" },
    { localidad: "Medellín-La Candelaria", nombre: "Maruchenga", estrato: 2, sector: "Centro" },
    { localidad: "Medellín-La Candelaria", nombre: "Miraflorez -Buenos Aires", estrato: 2, sector: "Centro" },
    { localidad: "Medellín-La Candelaria", nombre: "Miraflotez- Buenos Aires", estrato: 2, sector: "Centro" },
    { localidad: "Medellín-Robledo", nombre: "Miranda", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Manrique", nombre: "Moravia", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-La Candelaria", nombre: "Niqitao", estrato: 2, sector: "Centro" },
    { localidad: "Medellín-Laureles", nombre: "Obrero", estrato: 3, sector: "Occidente" },
    { localidad: "Bello", nombre: "Bello Paralela", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Robledo", nombre: "Pedregal", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Popular", nombre: "Popular 1", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-Laureles", nombre: "Porvenir", estrato: 3, sector: "Occidente" },
    { localidad: "Bello", nombre: "Quintas De La Playa", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Robledo", nombre: "Robledo Bello Orizonte", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Robledo", nombre: "Robledo Parque", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Robledo", nombre: "Robledo Pilarica", estrato: 3, sector: "Occidente" },
    { localidad: "Medellín-Laureles", nombre: "Rodeo Alto", estrato: 4, sector: "Occidente" },
    { localidad: "Medellín-La Candelaria", nombre: "Rosario", estrato: 3, sector: "Centro" },
    { localidad: "Medellín-San Javier", nombre: "San Javier, Peñita", estrato: 2, sector: "Occidente" },
    { localidad: "Medellín-Santa Cruz", nombre: "Santa Cruz", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-Santo Domingo", nombre: "Santo Domngo La Torre", estrato: 2, sector: "Nororiente" },
    { localidad: "Bello", nombre: "Trapiche", estrato: 3, sector: "Norte" },
    { localidad: "Medellín-Villa Hermosa", nombre: "Villa Hermosa", estrato: 2, sector: "Nororiente" },
    { localidad: "Medellín-Villatina", nombre: "Villatina", estrato: 2, sector: "Nororiente" }

];
