export const barrios = [
    { nombre: "Chapinero", localidad: "Chapinero", estrato: 4, sector: "Norte" },
    { nombre: "Usaquén", localidad: "Usaquén", estrato: 5, sector: "Norte" },
    { nombre: "Teusaquillo", localidad: "Teusaquillo", estrato: 4, sector: "Centro" },
    { localidad: "Bosa", nombre: "El Recreo", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Los Naranjos", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Las Margaritas", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa del Río", estrato: 3, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa Javier", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Antonia Santos", estrato: 1, sector: "Sur" },
    { localidad: "Bosa", nombre: "Arborizadora Baja", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Arborizadora Alta", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Azucena", estrato: 1, sector: "Sur" },
    { localidad: "Bosa", nombre: "Betania", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Ciudadela El Recreo", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "El Corzo", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "El Jardín", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "El Palmar", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Escocia", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Gualoche", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Islandia", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Jiménez de Quesada", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Cabaña", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Estación", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Libertad", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Paz", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Vega", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "La Portada", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Las Margaritas Sector I", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Las Margaritas Sector II", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Los Olivos", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Nueva Granada", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Olarte", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Palestina", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Paso Ancho", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Santafé", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "San Bernardino", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "San José", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "San Pablo", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Santa Fe de Bosa", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa Anny", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa del Mar", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa Karen", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa Nidia", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Villa Sonia", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Carvajal", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Techo", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Américas Occidental", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Tintal", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Tintalito", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Patio Bonito", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Pastrana", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "El Socorro", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Nuevo Kennedy", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Timiza", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "El Amparo", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Bavaria", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Alsacia", estrato: 4, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Marsella", estrato: 4, sector: "Sur" },
    { localidad: "Kennedy", nombre: "La Hacienda", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Las Delicias", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Nelly", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Gran Britalia", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Mandaly", estrato: 4, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Visión", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Las Margaritas", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Alexandra", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Catania", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Moravia", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Usminia", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Roma", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Liza", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Nidia", estrato: 3, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Villa Sonia", estrato: 3, sector: "Sur" },
    { localidad: "Chapinero", nombre: "Chicó", estrato: 6, sector: "Norte" },
    { localidad: "Chapinero", nombre: "Rosalía", estrato: 5, sector: "Norte" },
    { localidad: "Chapinero", nombre: "Rincón del Chicó", estrato: 6, sector: "Norte" },
    { localidad: "Chapinero", nombre: "La Loma", estrato: 5, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Siete de Agosto", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chapinero Central", estrato: 4, sector: "Centro" },
    { localidad: "Chapinero", nombre: "El Lago", estrato: 5, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Quintanares", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Rincón de Chapinero", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "La Porciúncula", estrato: 2, sector: "Centro" },
    { localidad: "Chapinero", nombre: "San Luis", estrato: 2, sector: "Centro" },
    { localidad: "Chapinero", nombre: "El Recuerdo", estrato: 2, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Las Ferias", estrato: 2, sector: "Centro" },
    { localidad: "Chapinero", nombre: "La Esperanza", estrato: 2, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chapinero Alto", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chapinero Bajo", estrato: 4, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Quinta Camacho", estrato: 4, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chapinero Occidental", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chapinero Centro", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "Santa Bárbara", estrato: 6, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Santa Ana", estrato: 6, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Verbenal", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Cedritos", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "El Country", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "La Floresta", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Pinar del Norte", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Buenavista", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "San Antonio", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Los Rosales", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "El Country Club", estrato: 6, sector: "Norte" },
    { localidad: "Usaquén", nombre: "La Carolina", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "La Alhambra", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Barrancas", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "El Contador", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Santa Paula", estrato: 6, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Bellavista", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "El Verbenal", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "San Antonio Norte", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "La Uribe", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Usaquén", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Pinar del Río", estrato: 3, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Usaquén Central", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "La Alameda", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "San José de Bavaria", estrato: 5, sector: "Norte" },
    { localidad: "Suba", nombre: "Suba Urbano", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Ciudad Jardín Norte", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "La Floresta", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Tibabuyes", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Niza Suba", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "La Gaitana", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Villa Cindy", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Las Villas", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Pontetresa", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "Los Arrayanes", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "La Uribe", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Prado Veraniego", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Rincón de Suba", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Suba Naranjos", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "Cafam la Colina", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Suba Cerros", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Suba Aures", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "San Cayetano", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "El Rincón", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "Britalia", estrato: 2, sector: "Norte" },
    { localidad: "Suba", nombre: "Suba Gaitana", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Niza", estrato: 4, sector: "Norte" },
    { localidad: "Engativá", nombre: "Bonanza", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Villa Gladys", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "El Porvenir", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Los Ángeles", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Engativá Central", estrato: 4, sector: "Centro" },
    { localidad: "Engativá", nombre: "La Felicidad", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Betania", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Tibabuyes", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "Villa Luz", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "San Ignacio", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Minuto de Dios", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Bosque de Modelia", estrato: 4, sector: "Centro" },
    { localidad: "Engativá", nombre: "Villa Amalia", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "Modelia", estrato: 4, sector: "Centro" },
    { localidad: "Engativá", nombre: "Villa Mayor", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "Cedritos", estrato: 4, sector: "Centro" },
    { localidad: "Engativá", nombre: "Los Álamos", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "La Granja", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "Santa Rosa", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "San Antonio", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "El Palmar", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "Villa Claudia", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "La Capilla", estrato: 2, sector: "Centro" },
    { localidad: "Engativá", nombre: "La Chucua", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibón Centro", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Modelia", estrato: 4, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Alamos", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibón Residencial", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "La Giralda", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "San Pablo", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Zona Franca", estrato: 4, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Modelia II", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibón Industrial", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Villa del Río", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Bochica", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Modelia Occidental", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Ciudad Salitre", estrato: 4, sector: "Centro" },
    { localidad: "Fontibón", nombre: "San José", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Villas de Granada", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "La Sabana", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "El Refugio", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Gualoche", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Lagos de Timiza", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Timiza", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontanar del Río", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Villa Claudia", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Villa de los Alpes", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Puerta de Teja", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Santa Helena", estrato: 2, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Teusaquillo Centro", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Quinta Paredes", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "La Esmeralda", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Ciudad Salitre", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Salitre Plaza", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Gran América", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Acevedo Tejada", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Porciúncula", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Mirasol", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Quirinal", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Modelia II", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Ciudad Montes", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Metrópolis", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Niza Norte", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Santa Ana", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "San Martín", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Quinta Camacho", estrato: 5, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Eduardo Santos", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Paloquemao", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Siete de Agosto", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Villa Mayor", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Galán", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Parque Central Bavaria", estrato: 4, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "Cataluña", estrato: 3, sector: "Centro" },
    { localidad: "Rafael Uribe Uribe", nombre: "Marco Fidel Suárez", estrato: 3, sector: "Centro" },
    { localidad: "Rafael Uribe Uribe", nombre: "San Jorge Central", estrato: 2, sector: "Centro" },
    { localidad: "Rafael Uribe Uribe", nombre: "Granjas de San Pablo", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "San Francisco", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Quiroga", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Ciudad Jardín", estrato: 3, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "San Jorge", estrato: 3, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Santa Isabel", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Los Cerezos", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Brasilia", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "La Victoria", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "El Paraíso", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "San Marcos", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Doce de Octubre", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Gloria Lara de Echenique", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Ciudad Montes", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Bellavista", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "La Esmeralda", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "La Paz", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Nueva Gloria", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "San Carlos", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Santander", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Ciudad de los Almendros", estrato: 2, sector: "Sur" },
    { localidad: "Rafael Uribe Uribe", nombre: "Nueva Alsacia", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Altamira", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Las Guacamayas", estrato: 1, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Arborizadora Alta", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Arborizadora Baja", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Arborizadora Medio", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Barcelona", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Bosque Popular", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Buenavista", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Casa Blanca", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Casa de Teja", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Cataluña", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Cerros de Oriente", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Cerros de San José", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Cristo Rey", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Calvario", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Paraíso", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Refugio", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Triunfo", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Tunal", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "El Vergel", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Gran Britalia", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "Juan José Rondón", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "La Aurora", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "La Castellana", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "La Casona", estrato: 2, sector: "Sur" },
    { localidad: "San Cristóbal", nombre: "La Colorada", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "El Recreo", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Cordillera del Sur", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Lorenzo Alcantuz", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Tunjo", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Arabia", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "El Oasis", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Villa Nidia", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Altos de San Diego", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Arboretum", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "El Rincón de las Delicias", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "San Gabriel", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "El Tesoro", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Villa Mayor", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "San Luis", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Portal de Usme", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "La Mesa de Usme", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "La Libertad", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Gran Yomasa", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "El Tesoro de Usme", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Altos de Santa Helena", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Las Delicias de Usme", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "La Primavera", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "San Joaquín", estrato: 2, sector: "Sur" },
    { localidad: "Usme", nombre: "Villa Nelly", estrato: 2, sector: "Sur" },
    { localidad: "Santa Fe", nombre: "La Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Las Nieves", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Egipto", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "San Diego", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Las Aguas", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Concordia", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Perseverancia", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Santa Inés", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Veraguas", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Santa Librada", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Los Mártires", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Ciudad Berna", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Voto Nacional", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Macarena", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Las Cruces", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Parque Nacional", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Santa Fe", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Santa Isabel", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "San Victorino", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Favorita", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Las Cruces", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Lourdes", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "San Bernardo", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "San Martín", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Ciudad Berna", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Ciudad Jardín", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Ciudad Kennedy Sur", estrato: 3, sector: "Sur" },
    { localidad: "Antonio Nariño", nombre: "Granjas de Techo", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Juan XXIII", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "La Ceiba", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "La Fraguita", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "La Fragua", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "La Paz", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Marco Fidel Suárez", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Mariscal Sucre", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "San Jorge", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Santa Isabel", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Santa Rita", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Techo", estrato: 3, sector: "Centro" },
    { localidad: "Antonio Nariño", nombre: "Villanueva", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Ciudad Salitre Suroriental", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Doce de Octubre", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "El Recuerdo", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Granjas de San Pablo", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Industrial", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "La Felicidad", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "La Hortúa", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "La Paz", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Los Libertadores", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Modelia Occidental", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Monteblanco", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Policarpa Salavarrieta", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Puente Aranda", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Santa Isabel Occidental", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Santa Rita", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Rafael Industrial", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Francisco", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Francisco Sur", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Joaquín", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Miguel", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "San Pablo", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Santa Rita", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Versalles", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Alcazares", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Alfonso López", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Altamira", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Atenas", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Batán", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Batán Lote", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Belmira", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Benjamín Herrera", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Bonanza", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Boyacá Real", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Brasilia", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Buenos Aires", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Cabo Lino", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Calvo Sur", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Campiña Norte", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Cataluña", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Chico Sur", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Ciudad Jardín Norte", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Ciudad Salitre", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Coopresa", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Cristóbal Colón", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Diana Turbay", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Eduardo Santos", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Egipto", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Espinosa", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Estadio", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Fátima", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Fátima II", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Fátima III", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Ferias", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Fernando Mazuera", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Florida", estrato: 3, sector: "Centro" },
    { localidad: "Barrios Unidos", nombre: "Florida Norte", estrato: 3, sector: "Centro" },
    { localidad: "Ciudad Bolívar", nombre: "Arborizadora Alta", estrato: 1, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Arborizadora Baja", estrato: 1, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Arborizadora Baja II", estrato: 1, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Arborizadora Alta II", estrato: 1, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Atenas Sur", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Bellavista", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Brasil", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Buenos Aires", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Carlos Lleras Restrepo", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Carvajal", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Casa Loma Sur", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Cataluña", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Ciudad Londres", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Ciudad Tesoro", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Cristo Rey", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "El Mirador", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "El Pesebre", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "El Tesoro", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Gran Yomasa", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Horacio Orjuela", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Ismael Perdomo", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Jericó Sur", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Cabaña", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Chiguaza", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Esperanza", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Estancia", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Gloria", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Paz", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Pradera", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Requilina", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "La Unión", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Sierra Morena", estrato: 1, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciudad Verde", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciudadela Sucre", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciudadela Terreros", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Limonar", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Levante de Ciudad Verde", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Norbac", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Palmira", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Portal de Santa Ana", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Santo Domingo", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Soacha Centro", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Soacha Parque", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Soacha Real", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Terreros", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Terralta", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Villa Nueva", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Villasantana", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Altos de Cazuca", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Altos de la Florida", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Altos de la Sabana", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Altos de San Mateo", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Altos de Soacha", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Brisas del Salitre", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Cazuca", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciénega Grande", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciudadela El Indio", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Altico", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Oasis", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Palmar", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Porvenir", estrato: 2, sector: "Sur" },
    { localidad: "Soacha", nombre: "El Salitre", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Alquería", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Betania", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Candelaria La Nueva", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Ciudad Tunal", estrato: 3, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "El Tesoro", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "La Picota", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Nueva Castilla", estrato: 2, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Patio Bonito", estrato: 2, sector: "Sur" },
    { localidad: "Usaquén", nombre: "Cedritos", estrato: 4, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "20 De Julio", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "Alameda", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Alameda Usaquén", estrato: 5, sector: "Norte" },
    { localidad: "Suba", nombre: "Alamos Norte", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Alcalá", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Alejandría", estrato: 3, sector: "Norte" },
    { localidad: "Fontibón", nombre: "Alqueria", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Amamos Norte", estrato: 2, sector: "Norte" },
    { localidad: "Kennedy", nombre: "America Occidental", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Américas Central", estrato: 3, sector: "Sur" },
    { localidad: "Fontibón", nombre: "Arrazan Bajo", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Atagualpa", estrato: 4, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Atenas", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Batan", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "Bella Suiza", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Bilbao", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Bochica", estrato: 2, sector: "Norte" },
    { localidad: "Bosa", nombre: "Bolivia", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Bosa Escocia", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Bosa La Amistad", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Bosa Libertad", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Bosa Recreo", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Bosa San José", estrato: 2, sector: "Sur" },
    { localidad: "Fontibón", nombre: "Bosque Popular", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Bosques De Suba", estrato: 3, sector: "Norte" },
    { localidad: "Fontibón", nombre: "Bravo Paes", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Cafan Floresta", estrato: 3, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "Calatrava", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Candelaria La Antigua", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Candelaria La Nueva", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Capuchina", estrato: 3, sector: "Centro" },
    { localidad: "Engativa", nombre: "Carvajal", estrato: 3, sector: "Centro" },
    { localidad: "Kennedy", nombre: "Castilla", estrato: 3, sector: "Sur" },
    { localidad: "Usaquén", nombre: "Cedrito", estrato: 4, sector: "Norte" },
    { localidad: "Kennedy", nombre: "Centro Américas", estrato: 2, sector: "Sur" },
    { localidad: "Chapinero", nombre: "Chapinero", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Chico", estrato: 5, sector: "Norte" },
    { localidad: "Chapinero", nombre: "Chico Norte", estrato: 6, sector: "Norte" },
    { localidad: "Ciudad Bolívar", nombre: "Ciudad Bolívar La Estrella", estrato: 2, sector: "Sur" },
    { localidad: "Antonio Nariño", nombre: "Ciudad Jardín Sur", estrato: 3, sector: "Sur" },
    { localidad: "Puente Aranda", nombre: "Ciudad Montes", estrato: 3, sector: "Sur" },
    { localidad: "Soacha", nombre: "Ciudad Verde Soacha", estrato: 2, sector: "Sur" },
    { localidad: "Suba", nombre: "Ciudadela Colsubsidio", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Colina", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Colina Campestre", estrato: 4, sector: "Norte" },
    { localidad: "Fontibón", nombre: "Cortijo", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Costa Sul Suba", estrato: 2, sector: "Norte" },
    { localidad: "Bosa", nombre: "Country Sur", estrato: 3, sector: "Sur" },
    { localidad: "Cundinamarca", nombre: "Cundinamarca", estrato: 2, sector: "Sur" },
    { localidad: "Santa Fe", nombre: "Dan Cristóbal Norte", estrato: 3, sector: "Centro" },
    { localidad: "Kennedy", nombre: "Diana Turbay", estrato: 2, sector: "Sur" },
    { localidad: "Suba", nombre: "El Galan", estrato: 2, sector: "Norte" },
    { localidad: "Fontibón", nombre: "El Recod", estrato: 2, sector: "Centro" },
    { localidad: "Engativa", nombre: "Engativa Alamos Norte", estrato: 2, sector: "Centro" },
    { localidad: "Engativa", nombre: "Engativa Sábanas Del Dorado", estrato: 2, sector: "Centro" },
    { localidad: "Engativa", nombre: "Engativo Pueblo", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fatima", estrato: 2, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Florida", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibon Hayuelos", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibon Salitre", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibón San Pablo", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Fontibon Zona Franca", estrato: 3, sector: "Centro" },
    { localidad: "Puente Aranda", nombre: "Galan Puente Aranda", estrato: 2, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Gran America", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Gran Granada", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Hayuelos", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Hipódromo", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Hipotecho", estrato: 3, sector: "Centro" },
    { localidad: "Engativa", nombre: "Jerusalén", estrato: 2, sector: "Centro" },
    { localidad: "Kennedy", nombre: "Kennedy America Central", estrato: 2, sector: "Sur" },
    { localidad: "Kennedy", nombre: "Kennedy Chicala", estrato: 2, sector: "Sur" },
    { localidad: "Engativa", nombre: "La Riveria", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "La Calleja", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "La Campiña Suba", estrato: 3, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "La Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Candelaria", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "La Clarita", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "La Concorde", estrato: 3, sector: "Centro" },
    { localidad: "Engativa", nombre: "La Estancia", estrato: 2, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Florida", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "La Fontana", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "La Fragua", estrato: 3, sector: "Norte" },
    { localidad: "Engativa", nombre: "La Gloria", estrato: 2, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "La Igualdad", estrato: 3, sector: "Centro" },
    { localidad: "Teusaquillo", nombre: "La Magdalena Teusaquillo", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "La Merced Norte", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "La Perseverancia", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "La Salle", estrato: 4, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "La Soledad", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "La Uribe", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Las Aguas", estrato: 4, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Las Cruces", estrato: 3, sector: "Centro" },
    { localidad: "Engativa", nombre: "Las Delicias", estrato: 2, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Lijaca Norte", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Los Pinares", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Lumbardia", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Luna Park", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Madelena", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Magdalena", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Mandalay", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Manuelita", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Marsella", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Mazuren", estrato: 3, sector: "Norte" },
    { localidad: "Fontibón", nombre: "Modelia", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "Niza", estrato: 4, sector: "Norte" },
    { localidad: "Bosa", nombre: "Nueva Gloria", estrato: 2, sector: "Sur" },
    { localidad: "Suba", nombre: "Palatino", estrato: 3, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "Parque Central Bavaria", estrato: 3, sector: "Centro" },
    { localidad: "Usaquén", nombre: "Pasadena", estrato: 5, sector: "Norte" },
    { localidad: "Kennedy", nombre: "Patio Bonito", estrato: 3, sector: "Sur" },
    { localidad: "Usaquén", nombre: "Perdomo", estrato: 4, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Pinar", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Pinos De Lombardia Suba", estrato: 3, sector: "Norte" },
    { localidad: "Kennedy", nombre: "Plaza De Las Americas", estrato: 2, sector: "Centro" },
    { localidad: "Usaquén", nombre: "Polo Club", estrato: 5, sector: "Norte" },
    { localidad: "Suba", nombre: "Pontevedra", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Pradera Norte", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Prado Vega", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Prado Veraniego", estrato: 4, sector: "Norte" },
    { localidad: "Suba", nombre: "Primavera", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Puente Largo", estrato: 3, sector: "Norte" },
    { localidad: "Chapinero", nombre: "Quinta Camacho", estrato: 5, sector: "Norte" },
    { localidad: "Usaquén", nombre: "Quintanares", estrato: 5, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "Quiroga", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Ricaurte", estrato: 3, sector: "Centro" },
    { localidad: "Chapinero", nombre: "Rincon Del Chico", estrato: 6, sector: "Norte" },
    { localidad: "Santa Fe", nombre: "Rio Negro", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Rosal", estrato: 3, sector: "Centro" },
    { localidad: "Santa Fe", nombre: "Salitre", estrato: 3, sector: "Centro" },
    { localidad: "San Antonio", nombre: "San Antonio Centro", estrato: 3, sector: "Centro" },
    { localidad: "San Antonio", nombre: "San Antonio Norte", estrato: 3, sector: "Centro" },
    { localidad: "San Antonio", nombre: "San Antonio Sur", estrato: 3, sector: "Centro" },
    { localidad: "Tunjuelito", nombre: "San Carlos", estrato: 3, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Fatima", estrato: 2, sector: "Sur" },
    { localidad: "San Cristobal", nombre: "San Cristobal Sur", estrato: 2, sector: "Sur" },
    { localidad: "Santa Fe", nombre: "San José", estrato: 3, sector: "Centro" },
    { localidad: "San Jose", nombre: "San Jose De Babaria", estrato: 3, sector: "Centro" },
    { localidad: "Usaquen", nombre: "San Luis", estrato: 3, sector: ",Centro" },
    { localidad: "Tunjuelito", nombre: "Venecia", estrato: 3, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "San Vicente", estrato: 3, sector: "Sur" },
    { localidad: "Tunjuelito", nombre: "Tunal", estrato: 3, sector: "Sur" },
    { localidad: "Bosa", nombre: "San Bernardino", estrato: 2, sector: "Sur" },
    { localidad: "Bosa", nombre: "Porvenir", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Ismael Perdomo", estrato: 2, sector: "Sur" },
    { localidad: "Ciudad Bolívar", nombre: "Sierra Morena", estrato: 1, sector: "Sur" },
    { localidad: "Engativá", nombre: "Las Ferias", estrato: 3, sector: "Centro" },
    { localidad: "Engativá", nombre: "Santa Helenita", estrato: 3, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Capellanía", estrato: 4, sector: "Centro" },
    { localidad: "Fontibón", nombre: "Villemar", estrato: 3, sector: "Centro" },
    { localidad: "Suba", nombre: "San Cipriano", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Potosí", estrato: 3, sector: "Norte" },
    { localidad: "Suba", nombre: "Canaima", estrato: 3, sector: "Norte" }
];
