export const barrios = [

{ localidad: "Cali-Aguacatal", nombre: "1 De Mayo", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Alamos", estrato: 4, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Alcazares", estrato: 5, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Alfonso Lopez", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Almendros", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Altos De Menga", estrato: 5, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Barranquilla", estrato: 4, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Bella Suiza", estrato: 4, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Bosque", estrato: 4, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Brisas De Los Alamos", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "CIudad 2000", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Calipso", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Camino Real", estrato: 2, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Campiña", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Caney", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Chiminango", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Ciudad Cordoba", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Comuneros", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Cristobal Colon", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Departamental", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "El Bosque", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "El Guabal", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "El Morichal", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Flora Industrial", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Floralia", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Gaitán", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Granada", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Guabal", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Guayacanes", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "La Base", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "La Campiña", estrato: 2, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "La Flora", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "La Hacienda", estrato: 2, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "La Rivera", estrato: 5, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "La Selva", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Las Orquideas", estrato: 2, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Lauriano Gómez", estrato: 5, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Lopez", estrato: 3, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Los Andes", estrato: 4, sector: "Norte" },
{ localidad: "Cauca Norte", nombre: "Los Lagos", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Manuela Beltran", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Mariano Ramos", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Marroquin", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Melendez", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Menga", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Morichal", estrato: 3, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Nacional", estrato: 2, sector: "Sur" },
{ localidad: "Cauca Norte", nombre: "Palmeras Del Norte", estrato: 4, sector: "Norte" },
{ localidad: "El Pondaje", nombre: "Paseo De Comfandi", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Petecuy", estrato: 2, sector: "Sur" },
{ localidad: "El Pondaje", nombre: "Poblado", estrato: 3, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Popular", estrato: 2, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Portal De Comfandi", estrato: 3, sector: "Norte" },
{ localidad: "Cañaveralejo", nombre: "Quintas De Salomia", estrato: 3, sector: "Norte" },
{ localidad: "Cali-Aguacatal", nombre: "Refugio", estrato: 4, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Republica De Israel", estrato: 2, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Rivera", estrato: 2, sector: "Norte" },
{ localidad: "Cali-Aguacatal", nombre: "San Antonio", estrato: 4, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "San Luis", estrato: 3, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Santa Bárbara", estrato: 3, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Santa Elena", estrato: 3, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Santamonica Popular", estrato: 5, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Siloe", estrato: 1, sector: "Norte" },
{ localidad: "Cali-Aguacatal", nombre: "Torres De Comfandi", estrato: 4, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Troncal", estrato: 2, sector: "Norte" },
{ localidad: "Cañaveralejo", nombre: "Ulpisno Lloreda", estrato: 2, sector: "Norte" },
{ localidad: "Pance-Lili", nombre: "Valle Del Lili", estrato: 5, sector: "Sur" },
{ localidad: "Pance-Lili", nombre: "Vallegrande", estrato: 3, sector: "Sur" },
{ localidad: "Pance-Lili", nombre: "Villa Blanca", estrato: 3, sector: "Sur" },
{ localidad: "Cali-Aguacatal", nombre: "Villa Colombia", estrato: 4, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Villa Del Prado", estrato: 3, sector: "Norte" },
{ localidad: "Cali-Aguacatal", nombre: "Villa Del Sol", estrato: 2, sector: "Sur" },
{ localidad: "Cañaveralejo", nombre: "Vipasa", estrato: 5, sector: "Norte" },
{ localidad: "Cali-Aguacatal", nombre: "Yumbo Guabinas", estrato: 2, sector: "Norte" }
];
