// barrios.js
export const barrios = [
    { localidad: "Distrito de Barranquilla", nombre: "El Prado", estrato: 6, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Riomar", estrato: 6, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Altos del Limón", estrato: 5, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Villa Country", estrato: 5, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Las Mercedes", estrato: 4, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Villa Santos", estrato: 4, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Los Andes", estrato: 3, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "La Paz", estrato: 3, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "Las Tres Avemarías", estrato: 2, sector: "Norte" },
    { localidad: "Distrito de Barranquilla", nombre: "San Felipe", estrato: 2, sector: "Norte" },
    { localidad: "Suroriente", nombre: "Los Pinos", estrato: 4, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "Los Almendros", estrato: 4, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "San Vicente", estrato: 3, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "San José", estrato: 3, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "La Playa", estrato: 2, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "San Francisco", estrato: 2, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "Las Malvinas", estrato: 2, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "Villa Blanca", estrato: 2, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "La Sierrita", estrato: 1, sector: "Suroriente" },
    { localidad: "Suroriente", nombre: "El Pueblo", estrato: 1, sector: "Suroriente" },
    { localidad: "Metropolitana", nombre: "El Recreo", estrato: 2, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "San Felipe", estrato: 3, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "La Luz", estrato: 3, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "La Victoria", estrato: 3, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "El Porvenir", estrato: 3, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "La Pradera", estrato: 3, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Buenavista", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Monte Carlo", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "La Floresta", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Ciudad Jardín", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Las Palmas", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Las Flores", estrato: 4, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Riomar", estrato: 5, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Alto Prado", estrato: 5, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Villa Country", estrato: 6, sector: "Metropolitana" },
    { localidad: "Metropolitana", nombre: "Villa Santos", estrato: 6, sector: "Metropolitana" },
    { localidad: "Suroccidente", nombre: "Las Malvinas", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Pueblito", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "San Francisco", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Central", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Silencio", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Silencio II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Inmaculada", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Parque", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Nueva Esperanza", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Sierrita", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Carmen", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "San José Obrero", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Ciudadela 20 de Julio", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Blanca", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Paraíso", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Playa", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "El Parque II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Union", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Ciudad Modesto", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Barlovento", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Las Moras", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Ciudadela Metropolitana", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Central II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Deportiva", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Carolina", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Las Gardenias", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Chinita", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Santa Helena", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "La Esmeralda", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "San José Obrero II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Nuevo Horizonte", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Los Andes", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Altos de San Vicente", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Lipaya", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Ciudadela 20 de Julio II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Delicias", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Geminis", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Espana", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Rubiela", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Santos", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Selene", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Selene II", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Selene III", estrato: 2, sector: "Suroccidente" },
    { localidad: "Suroccidente", nombre: "Villa Selene IV", estrato: 2, sector: "Suroccidente" },
    { localidad: "Riomar", nombre: "Altos de Riomar", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Altos de Riomar II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Altos de Riomar III", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Ciudad Jardín", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Ciudad Jardín I", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Ciudad Jardín II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Golf", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Golf II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Golf III", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Prado", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Prado I", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "El Prado II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "La Floresta", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "La Floresta I", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "La Floresta II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Los Nogales", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Los Nogales II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Los Nogales III", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Miramar", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Miramar II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Riomar", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Riomar II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Riomar III", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Riomar IV", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Santa Ana", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Santa Ana I", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Santa Ana II", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Santa Ana III", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Santa Ana IV", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Villa Carolina", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Villa Santos", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Villa Santos I", estrato: 6, sector: "Riomar" },
    { localidad: "Riomar", nombre: "Villa Santos II", estrato: 6, sector: "Riomar" },
    { localidad: "Suroccidente", nombre: "La Ceiba", estrato: 2, sector: "Suroccidente"},
    { localidad: "Riomar", nombre: "Alameda Del Rio", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Alboraya", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Alfonso Lopez", estrato: 2, sector: "Sur" },
{ localidad: "Riomar", nombre: "Almendros", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Bella Vista", estrato: 5, sector: "Norte" },
{ localidad: "Suroriente", nombre: "Bosque", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Boston", estrato: 4, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Buena Esperanza", estrato: 3, sector: "Sur" },
{ localidad: "Riomar", nombre: "Buenavista", estrato: 5, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Buenos Aires", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Campito", estrato: 3, sector: "Centro" },
{ localidad: "Riomar", nombre: "Caribe Verde", estrato: 4, sector: "Norte" },
{ localidad: "Suroriente", nombre: "Carrizal", estrato: 2, sector: "Sur" },
{ localidad: "Metropolitana", nombre: "Centenario Soledad", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Cevillar", estrato: 3, sector: "Sur" },
{ localidad: "Riomar", nombre: "Ciudad Jardin", estrato: 4, sector: "Norte" },
{ localidad: "Suroriente", nombre: "Coordialidad", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Cuidadela Metropolitana", estrato: 3, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "El Carmen", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "El Valle", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Girasoles", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Kennedy", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "La Ceiba", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "La Concepción", estrato: 4, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "La Sierra", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "La Victoria", estrato: 3, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Las Delicias", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Las Nieves", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Las Palmas", estrato: 4, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Limon", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Los Andes", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Los Olivos", estrato: 4, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Los Robles", estrato: 2, sector: "Sur" },
{ localidad: "Riomar", nombre: "Magdalena", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Mercedes", estrato: 4, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Milagro", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Nueva Estrella", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Nueva Granada", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Nuevo Milenio", estrato: 3, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Olaya", estrato: 2, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Pitufos", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Pradera", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Rebolo", estrato: 2, sector: "Centro" },
{ localidad: "Riomar", nombre: "Recreo", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Rosario", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "San Felipe", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "San Isidoro", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "San José", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "San Luis", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Santo Domingo", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Santurio", estrato: 3, sector: "Centro" },
{ localidad: "Norte-Centro Histórico", nombre: "Sherasy", estrato: 3, sector: "Centro" },
{ localidad: "Suroriente", nombre: "Siete De Abril", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Simón Bolívar", estrato: 3, sector: "Centro" },
{ localidad: "Metropolitana", nombre: "Soledad 2000", estrato: 3, sector: "Sur" },
{ localidad: "Suroriente", nombre: "Sourdis", estrato: 2, sector: "Sur" },
{ localidad: "Norte-Centro Histórico", nombre: "Unión", estrato: 3, sector: "Centro" },
{ localidad: "Riomar", nombre: "Villa San Pablo", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Victoria", estrato: 3, sector: "Centro" },
{ localidad: "Riomar", nombre: "Villa Blanca", estrato: 4, sector: "Norte" },
{ localidad: "Riomar", nombre: "Villa Carolina", estrato: 5, sector: "Norte" },
{ localidad: "Metropolitana", nombre: "Villa Del Carmen", estrato: 2, sector: "Sur" },
{ localidad: "Riomar", nombre: "Villa Flor", estrato: 4, sector: "Norte" },
{ localidad: "Metropolitana", nombre: "Villa Mónaco/Soledad", estrato: 2, sector: "Sur" },
{ localidad: "Metropolitana", nombre: "Villa Muvdi", estrato: 2, sector: "Sur" },
{ localidad: "Metropolitana", nombre: "Villa Rey (Soledad)", estrato: 2, sector: "Sur" },
{ localidad: "Riomar", nombre: "Villa San Pablo", estrato: 4, sector: "Norte" },
{ localidad: "Riomar", nombre: "Villa San Pedro", estrato: 4, sector: "Norte" },
{ localidad: "Riomar", nombre: "Villa Sanpablo", estrato: 4, sector: "Norte" },
{ localidad: "Riomar", nombre: "Villa Sol", estrato: 4, sector: "Norte" },
{ localidad: "Riomar", nombre: "Villasancarlos", estrato: 4, sector: "Norte" },
{ localidad: "Norte-Centro Histórico", nombre: "Villate", estrato: 3, sector: "Centro" },
];
